name: CrazyK9s
favicon: null
layout_spectrum: 0.7471543150022626
typography_spectrum: 0.29149374389089644
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7458788671065122
  lightness: 0.02377062290906906
  saturation: 0.5607731556519866
  rhythmicContrast: 0.5183154235128313
purpose: []
