name: CrazyK9s
favicon: null
layout_spectrum: 0
typography_spectrum: 0.60907
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#255061'
    - '#cccccc'
    - '#999999'
    - '#6c6c6c'
  brandStrength: 0.875
  lightness: 0.02377062290906906
  saturation: 0.5607731556519866
  rhythmicContrast: 0.5183154235128313
purpose: []
